# Generated by Django 3.2.7 on 2021-11-30 23:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ejercicios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(verbose_name='Número de ejercicio')),
                ('instruccionEjercicio', models.TextField(max_length=1000, verbose_name='Instrucción de ejercicio')),
                ('ejercicio', models.TextField(max_length=1000, verbose_name='Ejercicio')),
            ],
            options={
                'verbose_name': 'Ejercicio',
                'verbose_name_plural': '4) Ejercicios',
                'ordering': ['idTema', 'numero'],
            },
        ),
        migrations.CreateModel(
            name='Lecciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(unique=True, verbose_name='Número de lección')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título de lección')),
                ('descripcion', models.TextField(max_length=3000, verbose_name='Descripción de lección')),
            ],
            options={
                'verbose_name': 'una Lección',
                'verbose_name_plural': '1) Lecciones',
                'ordering': ['numero'],
            },
        ),
        migrations.CreateModel(
            name='TipoEjercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoEjercicio', models.CharField(max_length=200, verbose_name='Tipo de ejercicio')),
                ('descripcion', models.TextField(max_length=1000, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Tipo Ejercicio',
                'verbose_name_plural': '5) Tipos de Ejercicios',
            },
        ),
        migrations.CreateModel(
            name='Temas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.FloatField(unique=True, verbose_name='Número de Tema')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('teoria', models.TextField(max_length=3000, verbose_name='Teoría')),
                ('numMinEjemplos', models.FloatField(verbose_name='Número minímo de ejemplos a consultar')),
                ('numMinEjercicios', models.FloatField(verbose_name='Número minímo de ejercicios a resolver')),
                ('idLeccion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='conocimiento.lecciones', verbose_name='Lección perteneciente')),
            ],
            options={
                'verbose_name': 'un Tema',
                'verbose_name_plural': '2) Temas',
                'ordering': ['idLeccion', 'numero'],
            },
        ),
        migrations.CreateModel(
            name='RespuestasAbiertas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respuesta', models.TextField(max_length=200, verbose_name='Respuesta')),
                ('idEjercicio', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='conocimiento.ejercicios', verbose_name='Respuesta de Ejercicio')),
            ],
            options={
                'verbose_name': 'una Respuesta abierta',
                'verbose_name_plural': '6) Respuestas Abiertas',
                'ordering': ['idEjercicio'],
            },
        ),
        migrations.AddField(
            model_name='ejercicios',
            name='idTema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='conocimiento.temas', verbose_name='Tema al que pertenece'),
        ),
        migrations.AddField(
            model_name='ejercicios',
            name='idTipoEjercicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='conocimiento.tipoejercicio', verbose_name='Tipo de ejercicio'),
        ),
        migrations.CreateModel(
            name='RespuestasOpcionMultiple',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(verbose_name='Número de respuesta')),
                ('respuesta', models.TextField(max_length=200, verbose_name='Respuesta')),
                ('correctoIncorrecto', models.BooleanField(verbose_name='¿Es la respuesta correcta?')),
                ('idEjercicio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='conocimiento.ejercicios', verbose_name='Ejercicio')),
            ],
            options={
                'verbose_name': 'Respuestas Opcion Multiple',
                'verbose_name_plural': '7) Respuestas Opcion Multiple',
                'ordering': ['idEjercicio', 'numero'],
                'unique_together': {('numero', 'idEjercicio')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='ejercicios',
            unique_together={('numero', 'idTema')},
        ),
        migrations.CreateModel(
            name='Ejemplos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(verbose_name='Número de Ejemplo')),
                ('explicacion', models.TextField(max_length=1000, verbose_name='Explicación')),
                ('ejemplo', models.TextField(max_length=1000, verbose_name='Ejemplo')),
                ('idTema', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='conocimiento.temas', verbose_name='Tema al que pertenece')),
            ],
            options={
                'verbose_name': 'un Ejemplo',
                'verbose_name_plural': '3) Ejemplos',
                'ordering': ['idTema', 'numero'],
                'unique_together': {('numero', 'idTema')},
            },
        ),
    ]
