# Generated by Django 3.2.7 on 2021-11-30 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conocimiento', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temas',
            name='numMinEjemplos',
            field=models.IntegerField(verbose_name='Número minímo de ejemplos a consultar'),
        ),
        migrations.AlterField(
            model_name='temas',
            name='numMinEjercicios',
            field=models.IntegerField(verbose_name='Número minímo de ejercicios a resolver'),
        ),
    ]
