# Generated by Django 3.2.7 on 2021-12-09 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conocimiento', '0002_auto_20211130_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temas',
            name='numero',
            field=models.CharField(help_text='Ejemplo: 1.1', max_length=20, unique=True, verbose_name='Número de Tema'),
        ),
    ]
