# Generated by Django 3.2.7 on 2022-01-10 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conocimiento', '0004_ejercicios_ayuda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ejemplos',
            name='ejemplo',
            field=models.TextField(max_length=10000, verbose_name='Ejemplo'),
        ),
        migrations.AlterField(
            model_name='ejemplos',
            name='explicacion',
            field=models.TextField(max_length=10000, verbose_name='Explicación'),
        ),
        migrations.AlterField(
            model_name='ejercicios',
            name='ayuda',
            field=models.TextField(max_length=10000, verbose_name='Ayuda'),
        ),
        migrations.AlterField(
            model_name='ejercicios',
            name='ejercicio',
            field=models.TextField(max_length=10000, verbose_name='Ejercicio'),
        ),
        migrations.AlterField(
            model_name='ejercicios',
            name='instruccionEjercicio',
            field=models.TextField(max_length=10000, verbose_name='Instrucción de ejercicio'),
        ),
        migrations.AlterField(
            model_name='lecciones',
            name='descripcion',
            field=models.TextField(max_length=10000, verbose_name='Descripción de lección'),
        ),
        migrations.AlterField(
            model_name='respuestasabiertas',
            name='respuesta',
            field=models.TextField(max_length=10000, verbose_name='Respuesta'),
        ),
        migrations.AlterField(
            model_name='respuestasopcionmultiple',
            name='respuesta',
            field=models.TextField(max_length=10000, verbose_name='Respuesta'),
        ),
        migrations.AlterField(
            model_name='temas',
            name='teoria',
            field=models.TextField(max_length=10000, verbose_name='Teoría'),
        ),
        migrations.AlterField(
            model_name='tipoejercicio',
            name='descripcion',
            field=models.TextField(max_length=10000, verbose_name='Descripción'),
        ),
    ]
