# Generated by Django 3.2.7 on 2021-11-30 23:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('conocimiento', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edad', models.IntegerField(verbose_name='Edad')),
                ('ocupacion', models.CharField(max_length=200, verbose_name='Ocupación del estudiante')),
            ],
            options={
                'verbose_name': 'un Estudiante',
                'verbose_name_plural': '1) Estudiantes',
                'ordering': ['nombreUsuario'],
            },
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genero', models.CharField(max_length=50, verbose_name='Genero')),
            ],
            options={
                'verbose_name': 'un Genero',
                'verbose_name_plural': '6) Genero',
            },
        ),
        migrations.CreateModel(
            name='GradoMaximoEstudios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grado', models.CharField(max_length=100, verbose_name='Grado máximo de estudios')),
            ],
            options={
                'verbose_name': 'un Grado Máximo Estudios',
                'verbose_name_plural': '7) Grado Máximo Estudios',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='LeccionesEstudiadas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avance', models.IntegerField(verbose_name='Avance en la Lección')),
                ('terminada', models.BooleanField(verbose_name='¿Está terminada?')),
                ('idEstudiante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='estudiante.estudiante', verbose_name='Estudiante')),
                ('idLeccion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='conocimiento.lecciones', verbose_name='Lección')),
            ],
            options={
                'verbose_name': 'una Lección Estudiada',
                'verbose_name_plural': '2) Lecciones Estudiadas',
                'ordering': ['idLeccion', 'avance'],
                'unique_together': {('idLeccion', 'idEstudiante')},
            },
        ),
        migrations.CreateModel(
            name='TemasEstudiados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avanceEjemplos', models.IntegerField(verbose_name='Avance en ejemplos')),
                ('avanceEjercicios', models.IntegerField(verbose_name='Avance en ejercicios')),
                ('ejemplosExtra', models.IntegerField(verbose_name='Ejemplos extra')),
                ('ejerciciosExtra', models.IntegerField(verbose_name='Ejercicios extra')),
                ('terminada', models.BooleanField(verbose_name='¿Está terminado?')),
                ('idLeccionesEstudiadas', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='estudiante.leccionesestudiadas', verbose_name='Relación de Lección con Estudiante')),
                ('idTema', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='conocimiento.temas', verbose_name='Tema')),
            ],
            options={
                'verbose_name': 'un Tema Estudiado',
                'verbose_name_plural': '3) Temas Estudiados',
                'ordering': ['idTema'],
                'unique_together': {('idTema', 'idLeccionesEstudiadas')},
            },
        ),
        migrations.AddField(
            model_name='estudiante',
            name='genero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='estudiante.genero', verbose_name='Genero del estudiante'),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='gradoMaximoEstudios',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='estudiante.gradomaximoestudios', verbose_name='Grado máximo de estudios'),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='nombreUsuario',
            field=models.OneToOneField(help_text='Tu nombre plox', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Nombre del estudiante'),
        ),
        migrations.CreateModel(
            name='EjerciciosEstudiados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bien_o_Mal', models.BooleanField(verbose_name='Bien o mal')),
                ('pidioAyuda', models.BooleanField(verbose_name='Pidio ayuda')),
                ('tiempo', models.IntegerField(verbose_name='Tiempo en minutos')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('idEjercicio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='conocimiento.ejercicios', verbose_name='Ejercicio')),
                ('idTemaEstudiado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='estudiante.temasestudiados', verbose_name='Relación de Lección y Tema con Estudiante')),
            ],
            options={
                'verbose_name': 'un Ejercicio Estudiado',
                'verbose_name_plural': '5) Ejercicios Estudiados',
                'ordering': ['idEjercicio', 'fecha', 'tiempo', 'bien_o_Mal'],
            },
        ),
        migrations.CreateModel(
            name='EjemplosEstudiados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tiempo', models.IntegerField(verbose_name='Tiempo en minutos')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('idEjemplo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='conocimiento.ejemplos', verbose_name='Ejemplo')),
                ('idTemasEstudiados', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='estudiante.temasestudiados', verbose_name='Relación de Lección y Tema con Estudiante')),
            ],
            options={
                'verbose_name': 'un Ejemplo Estudiado',
                'verbose_name_plural': '4) Ejemplos Estudiados',
                'ordering': ['idEjemplo', 'fecha', 'tiempo'],
            },
        ),
    ]
