# Generated by Django 3.2.7 on 2021-12-02 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiante', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ejemplosestudiados',
            name='fecha',
            field=models.DateTimeField(verbose_name='Fecha'),
        ),
    ]
